### PR TITLE
GN-4556: Add editor styling

### PR DESCRIPTION
**Pull request by dkozickis**
## Overview

Add styles used in GN and editor to match the view.

The fix turned out to be way easier than expected (in code size at least).

##### connected issues and PRs:

https://binnenland.atlassian.net/browse/GN-4556

### Setup

1. Checkout
2. `npm i` 

### How to test/reproduce

1. Launch locally with `FASTBOOT_DISABLED=true ember s --proxy https://publicatie.gelinkt-notuleren.lblod.info/` 
2. Go to http://localhost:4200/Aalst/OCMW/zittingen/4aaa36f0-98f6-11ee-b234-65fc68d7dda7/uittreksels/fe1cc860-98f6-11ee-b234-65fc68d7dda7
4. Compare the result with https://publicatie.gelinkt-notuleren.lblod.info/Aalst/OCMW/zittingen/4aaa36f0-98f6-11ee-b234-65fc68d7dda7/uittreksels/fe1cc860-98f6-11ee-b234-65fc68d7dda7

CleanShot 2023-12-12 at 17 15 52@2x

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Comment by abeforgit** [comment]
what's this "might need to change BACKEND_URL"?

**Comment by abeforgit** [comment]
Ah and fastboot is failing cause you're proxying to a different host ok
that's the link I was looking for, cause if fastboot fails on prod we have a big problem.

**Review by piemonkey — COMMENTED** [review]
The changes seem good. Unfortunately, on this branch but not on master it refuses to load for me as there is no `<AuModalContainer />`, needed by the environment header. I think it's because the addition of the editor dep means that the header wants to display the packages overview. Unfortunately this requirement isn't in the readme for that package, it probably should be.

**Comment by abeforgit** [comment]
wait I didn't even notice this now pulls in the editor
not super keen on that, could we just duplicate the styles? There's nothing inherently tying these documents to the editor other than the fact they were created with it
I'd even prefer it if we have a more sensible css class/styling specification that we follow in the editor and document such that rendering platforms can style it as they see fit

**Review by abeforgit — CHANGES_REQUESTED** [review]
wait I didn't even notice this now pulls in the editor
not super keen on that, could we just duplicate the styles? There's nothing inherently tying these documents to the editor other than the fact they were created with it
I'd even prefer it if we have a more sensible css class/styling specification that we follow in the editor and document such that rendering platforms can style it as they see fit
that's out of scope here of course, but imo that's how we should approach it.
We just happen to want a style here that looks the same as the original style, but that's essentially a coincidence.

**Pull request merged**
