### PR TITLE
Remove unneeded dependencies

### PR DESCRIPTION
**Pull request by Windvis**
I think some of these things are leftovers from older blueprints but were kept during the upgrade.

### CODE REVIEW

**Comment by Windvis** [comment]
Seems like `postscribe` is needed for production builds. I couldn't find a reference to it in the app code though, and it didn't seem like a peerDependency of something else either.

**Comment by nvdk** [comment]
it's ember-cli-eslint that provides the warnings when running `ember serve` right? I quite like those to be honest. 
Re postscribe: there was a reason for not just having it as a dependency at the time, but I've forgotten it :). In any case I think we'll move away from the widget when we update the design to be more inline with its appuniversum brethren.

**Comment by Windvis** [comment]
> it's ember-cli-eslint that provides the warnings when running ember serve right?

Yes. Those projects aren't maintained anymore though. I wouldn't depend on them. And since the other projects don't use that setup anymore I figured it could be dropped here as well.

I have quite the opposite opinion about them though :smile:. They add unneeded noise to the cli output. If I want linting info I run the commands.

But I can add them back if you want.

**Comment by nvdk** [comment]
> But I can add them back if you want.

nah it's fine, but I will miss them :)

**Pull request merged**
